module.exports = {
  gameCodes: {
    0: 'pubg',
    1: 'freefire',
    2: 'pubg',
    3: 'pubg',
    4: 'pubg',
    5: 'pubg',
    6: 'pubg',
  },
  teams: [
    { name: 'TeamA' },
    { name: 'TeamB' },
    { name: 'TeamC' },
    { name: 'TeamD' },
    { name: 'TeamE' },
    { name: 'TeamF' },
    { name: 'TeamG' },
    { name: 'TeamH' },
    { name: 'TeamI' },
    { name: 'TeamJ' },
    { name: 'TeamK' },
    { name: 'TeamL' },
    { name: 'TeamM' },
    { name: 'TeamN' },
    { name: 'TeamO' },
    { name: 'TeamP' },
    { name: 'TeamQ' },
    { name: 'TeamR' },
    { name: 'TeamS' },
    { name: 'TeamT' },
    { name: 'TeamU' },
    { name: 'TeamV' },
    { name: 'TeamW' },
    { name: 'TeamX' },
    { name: 'TeamY' },
    { name: 'TeamZ' },
  ],
};
